deposit/urls.py
from django.urls import path
from . import views

app_name = 'deposit'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'), #/deposit/add
    path('update/<int:pk>/', views.update, name='update')
]

myown/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('deposit/', include('deposit.urls')),
]

polls/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

deposit/models.py
from django.db import models
from django.utils import timezone

class Aim(models.Model):
#   amount = models.IntegerField('設定金額', default='')
    amount = 600000

class Deposit(models.Model):
    id = models.AutoField(primary_key=True)
    date = models.DateTimeField(default=timezone.now)
    sent = models.IntegerField('入金額', default='')
    balance = models.IntegerField('残高', default='')

polls/models.py
from django.db import models

# Create your models here.

deposit/forms.py
from django import forms
from .models import Deposit


class DepositCreateForm(forms.ModelForm):

    class Meta:
        model = Deposit
#        fields = '__all__'
        fields = ('date')

deposit/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import DepositCreateForm
from .models import Deposit


def index(request):
    context = {
        'deposit_list': Deposit.objects.all(),
    }
    return render(request, 'deposit/deposit_list.html', context)


def add(request):
    # 送信内容を基にフォームを作る。POSTじゃなければ空のフォーム
    form = DepositCreateForm(request.POST or None)

    # method=POST、つまり送信ボタン押下時、入力内容が問題なければ
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('deposit:index')

    # 通常時のページアクセスや、入力内容に誤りがあればまたページを表示
    context = {
        'form':DepositCreateForm()
    }
    return render(request, 'deposit/deposit_form.html', context)

def update(request, pk):
  # urlのpkを基に、Depositを取得
  Deposit = get_object_or_404(Deposit, pk=pk)

  # フォームに、取得したDepositを紐づける
  form = DepositCreateForm(request.POST or None, instance=Deposit)

  # method=POST、つまり送信ボタン押下時、入力内容が問題なければ
  if request.method == 'POST' and form.is_valid():
    form.save()
    return redirect('deposit:index')

  # 通常時のページアクセスや、入力内容に誤りがあればまたページを表示
  context = {
    'form':form
  }
  return render(request, 'deposit/deposit_form.html', context)

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse


def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")

deposit/templates/deposit/account_form.html
{% extends 'deposit/base.html' %}

{% block content %}
<form action="" method="POST">
{{ form.as_p }}
<button type="submit">送信</button>
{% csrf_token %}
</form>
{% endblock %}

deposit/templates/deposit/base.html
<!doctype html>
<html lang="ja">
  <head>
    <title>アプリケーション</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  </head>
  <body>
  <div class="container">
    <nav class="nav">
     <a class="nav-link" href="{% url 'deposit:index' %}">一覧</a>
     <a class="nav-link" href="{% url 'deposit:add' %}">追加</a>
    </nav>
    {% block content %}
    {% endblock %}

   </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

deposit/templates/deposit/deposit_form.html
{% extends 'deposit/base.html' %}

{% block content %}
<form action="" method="POST">
{{ form.as_p }}
<button type="submit">送信</button>
{% csrf_token %}
</form>
{% endblock %}

deposit/templates/deposit/deposit_list.html
{% extends 'deposit/base.html' %}

{% block content %}
<h1>積み立てアプリ</h1>

<table class="table">
 <thead>
   <tr>
     <th>入金額</th>
     <th>残高</th>
   </tr>
  </thead>
  <tbody>
   {% for deposit in deposit_list %}
   <tr>
    <td>{{ deposit.sent }}</td>
    <td>{{ deposit.balance }}</td>
   </tr>
   {% endfor %}
  </tbody>
</table>
{% endblock %}